"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles, RefreshCw, Edit3, Save, Calendar, Send, Plus, Check,
  Hash, Languages, Users, Clock, Megaphone, Settings2, Image as ImageIcon,
  Wand2, AlertTriangle, Loader2, Upload, X,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { platformList, platformMeta } from "@/lib/platforms";
import { useStore } from "@/lib/store";
import { useGenerateContent, useCreatePost } from "@/lib/hooks/api";
import { api } from "@/lib/api-client";
import { EmptyState } from "../EmptyState";

const contentTypes = [
  "Post", "Caption", "Image Post", "Reel idea", "TikTok script",
  "YouTube description", "LinkedIn post", "Thread", "Story", "Comment", "Reply",
];
const tones = ["Professional", "Casual", "Witty", "Educational", "Inspirational", "Bold"];
const languages = ["English", "Urdu", "Hindi", "Arabic", "Spanish", "French", "German", "Chinese"];
const audiences = ["Founders", "Creators", "Marketers", "Developers", "Designers", "General"];

const pipeline = [
  { label: "Configure", done: true },
  { label: "Generate", done: false, active: true },
  { label: "Review", done: false },
  { label: "Schedule", done: false },
  { label: "Publish", done: false },
];

interface GeneratedVariant {
  label: string;
  tone: string;
  content: string;
  hashtags: string[];
  predictedEngagement: string;
  confidence: number;
}

export function CreateView() {
  const pushToast = useStore((s) => s.pushToast);
  const setView = useStore((s) => s.setView);
  const generateMutation = useGenerateContent();
  const createPostMutation = useCreatePost();

  const [platform, setPlatform] = useState<string>("instagram");
  const [contentType, setContentType] = useState("Caption");
  const [topic, setTopic] = useState("");
  const [tone, setTone] = useState("Educational");
  const [language, setLanguage] = useState("English");
  const [audience, setAudience] = useState("Developers");
  const [length, setLength] = useState("Medium");
  const [cta, setCta] = useState("");
  const [hashtags, setHashtags] = useState("");
  const [variants, setVariants] = useState<GeneratedVariant[]>([]);
  const [error, setError] = useState<string | null>(null);

  // Image generation state
  const [mediaMode, setMediaMode] = useState<"none" | "upload" | "generate">("none");
  const [imagePrompt, setImagePrompt] = useState("");
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [imageGenerating, setImageGenerating] = useState(false);

  const isImagePost = contentType === "Image Post";

  const generate = async () => {
    if (!topic.trim()) {
      setError("Please enter a topic first.");
      return;
    }
    setError(null);
    setVariants([]);
    try {
      const res = await generateMutation.mutateAsync({
        platform, contentType: isImagePost ? "Caption" : contentType,
        topic, tone, language, audience, length, cta, hashtags, variants: 3,
      });
      if (res.ok && Array.isArray(res.variants)) {
        setVariants(res.variants);
        pushToast({
          type: "success", title: "Generation complete",
          description: `${res.variants.length} variants generated by ${res.provider || "AI"}.`,
        });
      } else {
        setError("Generation returned no variants.");
      }
    } catch (err) {
      setError((err as Error).message || "Generation failed.");
    }
  };

  const generateImage = async () => {
    if (!imagePrompt.trim()) {
      pushToast({ type: "warning", title: "Please describe the image you want." });
      return;
    }
    setImageGenerating(true);
    setError(null);
    try {
      const res = await api.post<{ ok: boolean; base64?: string; error?: string; provider?: string }>(
        "/api/ai/generate-image",
        { prompt: imagePrompt, platform },
      );
      if (res.ok && res.base64) {
        setGeneratedImage(res.base64);
        pushToast({
          type: "success", title: "Image generated",
          description: `Image created by ${res.provider}. You can use it in your post.`,
        });
      } else {
        setError(res.error || "Image generation failed.");
      }
    } catch (err) {
      setError((err as Error).message || "Image generation failed.");
    }
    setImageGenerating(false);
  };

  const saveAsPost = async (variant: GeneratedVariant) => {
    try {
      await createPostMutation.mutateAsync({
        platform,
        type: contentType.toLowerCase().replace(/\s+/g, "-"),
        title: topic.slice(0, 80) || variant.content.slice(0, 60),
        caption: variant.content,
        hashtags: variant.hashtags,
        cta, tone: variant.tone, language, audience, status: "draft",
        media: generatedImage ? [generatedImage] : undefined,
      });
      pushToast({ type: "success", title: "Saved as draft", description: "Variant saved to your content library." });
    } catch (err) {
      pushToast({ type: "error", title: "Failed to save", description: (err as Error).message });
    }
  };

  return (
    <div className="grid grid-cols-1 xl:grid-cols-12 gap-4">
      {/* Left: configuration */}
      <div className="xl:col-span-4 space-y-4">
        <div className="rounded-xl border border-border bg-card/40 p-5">
          <div className="flex items-center gap-2 mb-4">
            <Settings2 className="h-4 w-4" />
            <h3 className="text-sm font-medium">Configuration</h3>
          </div>

          <Field label="Platform" icon={Megaphone}>
            <div className="grid grid-cols-4 gap-1.5">
              {platformList.map((p) => (
                <button key={p} onClick={() => setPlatform(p)}
                  className={cn("h-9 rounded-lg border text-[10px] font-medium transition-colors",
                    platform === p ? "border-white bg-white text-black" : "border-border bg-background/40 text-muted-foreground hover:bg-card")}>
                  {platformMeta[p].glyph}
                </button>
              ))}
            </div>
          </Field>

          <Field label="Content type" icon={Edit3}>
            <SelectChips options={contentTypes} value={contentType} onChange={setContentType} />
          </Field>

          {/* Image Post: show Upload / Generate toggle */}
          {isImagePost && (
            <Field label="Media" icon={ImageIcon}>
              <div className="flex gap-2 mb-3">
                <button onClick={() => setMediaMode("upload")}
                  className={cn("flex-1 rounded-lg border h-9 text-xs flex items-center justify-center gap-1.5 transition-colors",
                    mediaMode === "upload" ? "border-white bg-white text-black" : "border-border hover:bg-card")}>
                  <Upload className="h-3.5 w-3.5" /> Upload
                </button>
                <button onClick={() => setMediaMode("generate")}
                  className={cn("flex-1 rounded-lg border h-9 text-xs flex items-center justify-center gap-1.5 transition-colors",
                    mediaMode === "generate" ? "border-white bg-white text-black" : "border-border hover:bg-card")}>
                  <Sparkles className="h-3.5 w-3.5" /> Generate with AI
                </button>
              </div>

              {mediaMode === "upload" && (
                <div className="rounded-lg border border-dashed border-border p-4 text-center">
                  <input type="file" accept="image/*" className="hidden" id="file-upload"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) {
                        const reader = new FileReader();
                        reader.onload = () => setGeneratedImage(reader.result as string);
                        reader.readAsDataURL(file);
                      }
                    }} />
                  <label htmlFor="file-upload" className="cursor-pointer">
                    <Upload className="h-5 w-5 text-muted-foreground mx-auto mb-2" />
                    <div className="text-xs">Click to upload</div>
                    <div className="text-[10px] text-muted-foreground mt-0.5">PNG, JPG up to 10MB</div>
                  </label>
                </div>
              )}

              {mediaMode === "generate" && (
                <div className="space-y-2">
                  <textarea value={imagePrompt} onChange={(e) => setImagePrompt(e.target.value)}
                    placeholder="Describe the image you want to generate..."
                    rows={2}
                    className="w-full rounded-lg border border-border bg-background/40 px-3 py-2 text-sm outline-none focus:border-white/30 resize-none placeholder:text-muted-foreground" />
                  <button onClick={generateImage} disabled={imageGenerating || !imagePrompt.trim()}
                    className="w-full rounded-lg bg-white text-black h-9 text-xs font-medium hover:bg-white/90 transition-colors disabled:opacity-60 inline-flex items-center justify-center gap-2">
                    {imageGenerating ? <><Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating image...</> : <><Sparkles className="h-3.5 w-3.5" /> Generate Image</>}
                  </button>
                </div>
              )}

              {/* Generated/Uploaded image preview */}
              {generatedImage && (
                <div className="mt-3 relative rounded-lg overflow-hidden border border-border">
                  <img src={generatedImage} alt="Generated" className="w-full" />
                  <button onClick={() => setGeneratedImage(null)}
                    className="absolute top-2 right-2 h-7 w-7 rounded-full bg-black/60 backdrop-blur flex items-center justify-center text-white hover:bg-red-500 transition-colors">
                    <X className="h-3.5 w-3.5" />
                  </button>
                  {mediaMode === "generate" && (
                    <button onClick={generateImage} disabled={imageGenerating}
                      className="absolute bottom-2 right-2 rounded-lg bg-white text-black px-2 py-1 text-[10px] font-medium inline-flex items-center gap-1 disabled:opacity-60">
                      <RefreshCw className={cn("h-3 w-3", imageGenerating && "animate-spin")} /> Regenerate
                    </button>
                  )}
                </div>
              )}
            </Field>
          )}

          <Field label="Topic" icon={Sparkles}>
            <textarea value={topic} onChange={(e) => setTopic(e.target.value)}
              placeholder="What should the AI write about?"
              rows={2}
              className="w-full rounded-lg border border-border bg-background/40 px-3 py-2 text-sm outline-none focus:border-white/30 transition-colors resize-none placeholder:text-muted-foreground" />
          </Field>

          <Field label="Tone" icon={Wand2}>
            <SelectChips options={tones} value={tone} onChange={setTone} />
          </Field>

          <Field label="Language" icon={Languages}>
            <SelectChips options={languages} value={language} onChange={setLanguage} />
          </Field>

          <Field label="Audience" icon={Users}>
            <SelectChips options={audiences} value={audience} onChange={setAudience} />
          </Field>

          <Field label="Length" icon={Clock}>
            <SelectChips options={["Short", "Medium", "Long"]} value={length} onChange={setLength} />
          </Field>

          <Field label="Call-to-action" icon={Megaphone}>
            <input value={cta} onChange={(e) => setCta(e.target.value)} placeholder="Optional CTA"
              className="w-full rounded-lg border border-border bg-background/40 h-10 px-3 text-sm outline-none focus:border-white/30 transition-colors" />
          </Field>

          <Field label="Hashtags" icon={Hash}>
            <input value={hashtags} onChange={(e) => setHashtags(e.target.value)} placeholder="Optional hashtags"
              className="w-full rounded-lg border border-border bg-background/40 h-10 px-3 text-sm outline-none focus:border-white/30 transition-colors" />
          </Field>

          <button onClick={generate} disabled={generateMutation.isPending}
            className="w-full mt-2 rounded-lg bg-white text-black h-10 text-sm font-medium hover:bg-white/90 transition-colors disabled:opacity-60 inline-flex items-center justify-center gap-2">
            {generateMutation.isPending ? <><Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating...</> : <><Sparkles className="h-3.5 w-3.5" /> {isImagePost ? "Generate caption" : "Generate variants"}</>}
          </button>

          {error && (
            <div className="mt-3 rounded-lg border border-red-400/30 bg-red-400/[0.05] p-2.5 flex items-start gap-2">
              <AlertTriangle className="h-3.5 w-3.5 text-red-400 shrink-0 mt-0.5" />
              <span className="text-[11px] text-red-300 leading-relaxed">{error}</span>
            </div>
          )}
        </div>

        {/* Pipeline */}
        <div className="rounded-xl border border-border bg-card/40 p-5">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4" />
              <h3 className="text-sm font-medium">Content Pipeline</h3>
            </div>
            <span className="text-[10px] text-muted-foreground font-mono">1/5</span>
          </div>
          <div className="space-y-1.5">
            {pipeline.map((step, i) => (
              <div key={step.label} className="flex items-center gap-2.5">
                <div className={cn("h-6 w-6 rounded-full border flex items-center justify-center text-[10px] shrink-0",
                  step.done && "bg-white border-white text-black",
                  step.active && "border-white bg-white/10",
                  !step.done && !step.active && "border-border text-muted-foreground")}>
                  {step.done ? <Check className="h-3 w-3" /> : <span>{i + 1}</span>}
                </div>
                <div className={cn("text-xs", step.active && "font-medium")}>{step.label}</div>
                {step.active && <span className="ml-auto text-[10px] text-white animate-pulse">in progress</span>}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Right: variants + image preview */}
      <div className="xl:col-span-8 space-y-4">
        {/* Image preview for Image Post */}
        {isImagePost && generatedImage && (
          <div className="rounded-xl border border-border bg-card/40 p-5">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="text-sm font-medium">Generated Image</h3>
                <p className="text-[11px] text-muted-foreground mt-0.5">This image will be attached to your post</p>
              </div>
            </div>
            <div className="rounded-lg overflow-hidden border border-border">
              <img src={generatedImage} alt="Post media" className="w-full max-h-96 object-contain" />
            </div>
          </div>
        )}

        <div className="rounded-xl border border-border bg-card/40 p-5">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-sm font-medium">Generated Variants</h3>
              <p className="text-[11px] text-muted-foreground mt-0.5">
                {variants.length === 0
                  ? isImagePost ? "Generate a caption for your image post" : "Configure on the left and click Generate variants"
                  : `${variants.length} variants for ${platformMeta[platform as keyof typeof platformMeta]?.name} · ${contentType}`}
              </p>
            </div>
            {variants.length > 0 && (
              <button onClick={generate} disabled={generateMutation.isPending}
                className="inline-flex items-center gap-1.5 rounded-lg border border-border h-8 px-3 text-xs hover:bg-accent transition-colors">
                <RefreshCw className={cn("h-3 w-3", generateMutation.isPending && "animate-spin")} />
                Regenerate
              </button>
            )}
          </div>

          {variants.length === 0 && !generateMutation.isPending && (
            <EmptyState icon={Sparkles} title="No variants yet"
              description={isImagePost
                ? "Write a prompt for your image, generate it, then generate a caption to go with it."
                : "Set your configuration and click Generate variants. The AI will produce distinct tone variants with predicted performance."} />
          )}

          {generateMutation.isPending && (
            <div className="space-y-3">
              {[1, 2, 3].map((i) => (
                <div key={i} className="rounded-lg border border-border bg-background/40 p-4">
                  <div className="flex items-center justify-between mb-3">
                    <div className="h-3 w-20 bg-white/5 animate-pulse rounded" />
                    <div className="h-3 w-12 bg-white/5 animate-pulse rounded" />
                  </div>
                  <div className="space-y-2">
                    <div className="h-3 w-full bg-white/5 animate-pulse rounded" />
                    <div className="h-3 w-4/5 bg-white/5 animate-pulse rounded" />
                    <div className="h-3 w-3/5 bg-white/5 animate-pulse rounded" />
                  </div>
                </div>
              ))}
            </div>
          )}

          <AnimatePresence>
            <div className="space-y-3">
              {variants.map((v, i) => (
                <motion.div key={`${v.label}-${i}`}
                  initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: i * 0.08 }}
                  className="rounded-lg border border-border bg-background/40 p-4">
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] font-mono text-muted-foreground">{v.label}</span>
                      <span className="rounded-full border border-border bg-card/60 px-2 py-0.5 text-[10px]">{v.tone}</span>
                      {v.predictedEngagement && (
                        <span className="rounded-full border border-white/20 bg-white/5 px-2 py-0.5 text-[10px] text-white">{v.predictedEngagement} engagement</span>
                      )}
                    </div>
                    <span className="text-[10px] text-muted-foreground">{Math.round((v.confidence || 0.8) * 100)}% confidence</span>
                  </div>
                  <p className="text-sm leading-relaxed whitespace-pre-wrap text-pretty">{v.content}</p>
                  {v.hashtags && v.hashtags.length > 0 && (
                    <div className="mt-3 flex flex-wrap gap-1.5">
                      {v.hashtags.map((h) => (
                        <span key={h} className="rounded-md border border-border bg-card/60 px-2 py-0.5 text-[10px] text-muted-foreground font-mono">{h}</span>
                      ))}
                    </div>
                  )}
                  <div className="mt-4 pt-3 border-t border-border flex items-center gap-2 flex-wrap">
                    <ActionButton icon={Save} label="Save as post" loading={createPostMutation.isPending} onClick={() => saveAsPost(v)} />
                    <ActionButton icon={Calendar} label="Schedule" onClick={() => saveAsPost(v).then(() => setView("calendar"))} />
                    <ActionButton icon={Plus} label="Add to queue" onClick={() => saveAsPost(v).then(() => setView("calendar"))} />
                    <button onClick={() => pushToast({ type: "success", title: "Publishing now", description: `${v.label} for ${platformMeta[platform as keyof typeof platformMeta]?.name} queued for publishing.` })}
                      className="ml-auto inline-flex items-center gap-1.5 rounded-lg bg-white text-black h-8 px-3 text-xs font-medium hover:bg-white/90 transition-colors">
                      <Send className="h-3 w-3" /> Publish
                    </button>
                  </div>
                </motion.div>
              ))}
            </div>
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}

function Field({ label, icon: Icon, children }: { label: string; icon: React.ComponentType<{ className?: string }>; children: React.ReactNode }) {
  return (
    <div className="mb-3.5">
      <div className="flex items-center gap-1.5 mb-1.5">
        <Icon className="h-3 w-3 text-muted-foreground" />
        <label className="text-[11px] text-muted-foreground">{label}</label>
      </div>
      {children}
    </div>
  );
}

function SelectChips({ options, value, onChange }: { options: string[]; value: string; onChange: (v: string) => void }) {
  return (
    <div className="flex flex-wrap gap-1.5">
      {options.map((opt) => (
        <button key={opt} onClick={() => onChange(opt)}
          className={cn("rounded-md px-2.5 h-7 text-[11px] transition-colors border",
            value === opt ? "border-white bg-white text-black" : "border-border bg-background/40 text-muted-foreground hover:bg-card")}>
          {opt}
        </button>
      ))}
    </div>
  );
}

function ActionButton({ icon: Icon, label, onClick, loading }: { icon: React.ComponentType<{ className?: string }>; label: string; onClick?: () => void; loading?: boolean }) {
  return (
    <button onClick={onClick} disabled={loading}
      className="inline-flex items-center gap-1.5 rounded-lg border border-border h-8 px-3 text-xs hover:bg-accent transition-colors disabled:opacity-60">
      {loading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Icon className="h-3 w-3" />}
      {label}
    </button>
  );
}
